title: "Resumo Semanal"
labels: documentation
body:
  - type: markdown
    value: "## Resultados da semana..."
  - type: markdown
    attributes:
      value: |
        ## O que foi feito nessa semana:

        - ✅ 
        - ✅ 
        - ✅ 
        - ✅ 

        ## O que fazer no próximo ciclo:

        - ⏭️ 
        - ⏭️ 
        - ⏭️
          - ⏭️
          - ⏭️
